### ISSUE TITLE
GitHub link package differs from composer file

### ISSUE THREAD

**Issue by nunomaduro** [beyondcode/laravel-xray#1]
Hey @mpociot 👋

Thanks for this package! Would be good rename the **GitHub link package** from `beyondcode/laravel-xray` to `beyondcode/laravel-view-xray`.

In order to keep the same name that already exists in `composer.json` and namespaces.

<img width="280" alt="screenshot 2018-07-19 13 24 55" src="https://user-images.githubusercontent.com/5457236/42939734-295c8028-8b57-11e8-9e95-306c8495b5e1.png">

<img width="349" alt="screenshot 2018-07-19 13 25 23" src="https://user-images.githubusercontent.com/5457236/42939747-38847a38-8b57-11e8-875f-10458bfd9a69.png">

**Comment by mpociot** [comment]
You're right - fixed it :)
