### ISSUE TITLE
xray display none but xray use true in .env

### ISSUE THREAD

**Issue by Rishats** [beyondcode/laravel-xray#13]
Laravel 5.6
PHP: 7.2
No error in log.
<img width="1440" alt="empty" src="https://user-images.githubusercontent.com/21194702/43688516-1b317d1a-990c-11e8-96cc-1be67eb7f797.png">

**Comment by mpociot** [comment]
This could be related to VueJS removing the comments. Have you tried setting `comments` to true, as suggested here: https://github.com/beyondcode/laravel-view-xray#faq ?

**Comment by Rishats** [comment]
@mpociot Yes, i tried this and also use ` npm run dev` after it but i still had this problem(
