### ISSUE TITLE
Linux/Chrome Hotkey Ctrl + Shift + X  doesn't seem to work

### ISSUE THREAD

**Issue by typoworx-de** [beyondcode/laravel-xray#16]
For Linux and Google Chrome Browser, the Hotkey Ctrl + Shift + X doesn't seem to work. The hotkey seems to be in use elsewhere (I don't know if it's chrome itself or an addon). Is it possible to change the hot-key for X-Ray using Configuration-File?

**Comment by mozgbrasil** [comment]
![captura de tela de 2018-09-11 18-17-45](https://user-images.githubusercontent.com/17202780/45388338-0b86e080-b5ef-11e8-88a1-e21ab376a399.png)
![captura de tela de 2018-09-11 18-17-59](https://user-images.githubusercontent.com/17202780/45388339-0b86e080-b5ef-11e8-8630-0ead715d659f.png)

**Comment by osbre** [comment]
Fact about Linux: In firefox shortcut will work (tested with Linux Mint 19)
(it's maybe a chrome-only problem)

## Update 2020:

Works well on Brave in Linux.
You just need to have JQuery on the page if you want to make this package works.
