### ISSUE TITLE
Laravel 5.7

### ISSUE THREAD

**Issue by stayallive** [beyondcode/laravel-xray#18]
I saw composer.json was already updated, could you please tag a release now 5.7 is out? ❤️

**Comment by mpociot** [comment]
Fixed in 1.1.0 :)

**Comment by stayallive** [comment]
Packagist is not updating (again)... https://packagist.org/packages/beyondcode/laravel-view-xray

Maybe the [new integration](https://packagist.org/about#how-to-update-packages) will work better 😅
