### ISSUE TITLE
Update PHP-Version requirement to PHP 8?

### ISSUE THREAD

**Issue by typoworx-de** [beyondcode/laravel-xray#25]
Hello,
is it possible to rise PHP-Version requirement to PHP 8? I'm currently unable to composer-require this package due to the strict requirement of ^php7.1 in your composer.json. Is it at least compatible to php7.4 or even php8.0?

**Comment by grafst** [comment]
yes, would be very cool!

**Comment by angeljqv** [comment]
@grafst beyondcode has no support
