### ISSUE TITLE
use a btn instead of shortcuts

### ISSUE THREAD

**Issue by ctf0** [beyondcode/laravel-xray#3]

**Comment by mpociot** [comment]
Any reason why?

**Comment by ctf0** [comment]
for more than a reason
- atm u need to support different ops keys "ctrl vs cmnd" 
- the user might have already assigned the same keys for something else "os level or site level"
- using a btn is much easier and u dont need to reach for ur keyboard each time u want to disable/enable as for debugging u r mostly going to use the mouse.
- using a shortcut means the user have to memorize it, what if there are more than one dev on the same project ?
- keycodes not persistent across browsers nor easy to maintain

**Comment by ctf0** [comment]
@mpociot any updates ?

**Comment by mpociot** [comment]
Do you want to provide a PR with the changes for this?

**Comment by ctf0** [comment]
do u want to keep the shortcuts or remove em ?
for btn styling, do you want it to be configurable or static?

and to make sure, this is the part that should be replaced

https://github.com/beyondcode/laravel-view-xray/blob/0c0f923b3b95b742b34430746ccdc467009dd7a6/resources/assets/xray.js#L17-L29

correct ?

**Comment by mpociot** [comment]
I guess we can just make the button styling static.
What do you think of having the shortcuts configurable? Not the actual keys, but the ability to enable/disable them?

And yes - that's the part that needs to be updated

**Comment by ctf0** [comment]
> What do you think of having the shortcuts configurable? Not the actual keys, but the ability to enable/disable them?

yeah why not, but if you are going to make it configurable why not go the extra mile and make the shortcut it self configurable ?

**on a side note,**
i was thinking maybe we can turn the whole UI into a browser extension, something like `vuejs, blackfire, etc..` but am not sure how it will be done :disappointed:

**Comment by mpociot** [comment]
> yeah why not, but if you are going to make it configurable why not go the extra mile and make the shortcut it self configurable ?

That's a great idea!

And I also thought about turning this (among other things) into a browser extension, but haven't found the time to look into it in more detail

**Comment by ctf0** [comment]
okay so to keep things simple, lets replace the shortcuts with a btn for now & the extra config could be added later to the browser ext, this way we won't need to do big changes to the package.

btw we can open a new issue for the browser ext idea, maybe someone can pick it up.

also i was thinking of dropping jquery, again it would make things easier when converting to an ext.
