### ISSUE TITLE
Conflicting Shortcuts

### ISSUE THREAD

**Issue by paulredmond** [beyondcode/laravel-xray#7]
When I first took this package for a spin I noticed that the shortcut conflicted with the [XDebug helper](https://chrome.google.com/webstore/detail/xdebug-helper/eadndfjplgieldjbigjakmdgkmoaaaoc?hl=pt-PT&authuser=1) Chrome extension at least on Mac: <kbd>command</kbd> + <kbd>shift</kbd> + <kbd>X</kbd>.

I don't know if this is an edge-case with any other extensions, but it might be useful to have configurable keyboard shortcuts or some kind of callback a user can register that the xray JS defers to.

I'm open to helping if you have any ideas, otherwise, at least documenting it here. ❤️

**Comment by mpociot** [comment]
This is related to #3 
We could either make the shortcut configurable or remove it entirely and add a visible button to toggle.

**Comment by ndberg** [comment]
Would be great to make i configurable, having a conflict too.
