### ISSUE TITLE
Shortcut not working

### ISSUE THREAD

**Issue by ahmadasjad** [beyondcode/laravel-xray#8]
I installed this plugin via composer, after installing I refreshed the web page, but it did nothing. I was doubtful either its content is loading or not, but its content is being loaded at last of the page source, but it's doing nothing. I haven't installed xbeug chrome extension that may conflict with the shortcut key.

**Comment by mpociot** [comment]
The current version requires jQuery. Maybe you don’t have jQuery installed?

**Comment by ahmadasjad** [comment]
Ok,
Great!

Just one suggestion, let you add this description to the doc. This will help others to run without interruption as I was not able to find about this dependency(jQuery) anywhere in the doc

Thanks
