### ISSUE TITLE
injectXrayBar needs api or route exclude

### ISSUE THREAD

**Issue by webtamizhan** [beyondcode/laravel-xray#9]
Hi there!
while trying to listen the auth broadcast channel receiving 

` "message": "Call to a member function getPath() on null","exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "C:\\xampp\\htdocs\\dev\\neomed-dev\\vendor\\beyondcode\\laravel-view-xray\\src\\XrayMiddleware.php",
    "line": 102,`

using 
Laravel 5.6.*,
beyondcode/laravel-view-xray  ^1.0,
Laravel echo server.

**Comment by mpociot** [comment]
This is now fixed in 1.0.3
